TARGET_RETENTION = 0.90
INITIAL_DIFFICULTY = 4.00
INITIAL_STABILITY = 1.00
PRIORITY_INTERVAL = 0.05

MIN_USERNAME_LENGTH = 4
MAX_USERNAME_LENGTH = 32
MIN_PASSWORD_LENGTH = 8

MIN_DIFFICULTY = 0
MAX_DIFFICULTY = 10

DEFAULT_LEVEL = 1

DEFAULT_DATABASE_LOCATION = "./Data/ProgramDatabase.db"